__use_yte__: true

dhps:
  gene_name: 'dhps'
  minqual: 15
  targetlen: 2742
  maxlen: ?this["dhps/targetlen"] + 250 #2992
  minlen: ?this["dhps/targetlen"] - 50 #2692
  generef: 'resources/dhps.fasta'
  genebank_ref: 'resources/dhps.jsonl'
  contig: 'NC_004329.3_dhps'

dhfr:
  gene_name: 'dhfr'
  minqual: 15
  targetlen: 1827
  maxlen: ?this["dhps/targetlen"] + 250 #2992
  minlen: ?this["dhps/targetlen"] - 50 #2692
  generef: 'resources/dhfr.fasta'
  genebank_ref: 'resources/dhfr.jsonl'
  contig: 'NC_004318.2_dhfr'