min_reads: 50
threshold: 0.05
minqual: 15

genes:
  dhps:
    targetlen: 2742
    maxlen: 2992 # IF LEFT EMPTY DEFAULTS TO TARGETLEN + 250
    minlen: 2692 # IF LEFT EMPTY DEFAULTS TO TARGETLEN - 50
    generef: 'resources/dhps.fasta'
    genebank_ref: 'resources/dhps.jsonl'
    contig: 'NC_004329.3_dhps'

  # dhfr:
  #   targetlen: 1827
  #   generef: 'resources/dhfr.fasta'
  #   genebank_ref: 'resources/dhfr.jsonl'
  #   contig: 'NC_004318.2_dhfr'

  testdhps:
    targetlen: 2742
    generef: 'resources/dhps.fasta'
    genebank_ref: 'resources/dhps.jsonl'
    contig: 'NC_004329.3_dhps'
